### ISSUE TITLE
BaseImporter::ConvertToUTF8() doesn't convert UTF-16

### ISSUE THREAD

**Issue by jpownby** [assimp/assimp#3247]
The conversion happens to a temporary vector named "output", but the converted data is then discarded. Also, I think the conversion itself isn't correct. Here is a possible fixed version I made trying to keep the same style from other places in the function:

        std::vector<char> output;
        uint16_t *ptr = (uint16_t*)&data[ 0 ];
        uint16_t *end = ptr + ( data.size() / sizeof(uint16_t) );
        ++ptr;	// Skip BOM
        utf8::utf16to8(ptr, end, back_inserter(output));
        data = output;

(Also, the UTF-32 conversion doesn't seem correct, although I haven't tested and have just looked at the code. I think "end" should probably be calculated the way I show above (no +1) and output should also be assigned to data as I show above. The BOM could also probably be skipped in the same way.)

**Comment by kimkulling** [comment]
WTF, thanks a lot for figuring this out. We need more unittests here I guess!

**Comment by jpownby** [comment]
Incidentally, I think I also discovered a related problem that would have to be fixed if ConvertToUTF8() is fixed:

In irrXMLWrapper.h, in the constructor for CIrrXML_IOStreamReader, there is code to remove NULL characters, and this happens before BaseImporter::ConvertToUTF8(data) is called. This works ok when ConvertToUTF8() doesn't do anything, but it causes problems when it is fixed as I propose in my first comment.

I think if the call to BaseImporter::ConvertToUTF8(data) is moved before the code to remove NULL characters then everything will behave as intended.

**Comment by tellypresence** [comment]
@jpownby Is this still a problem?

**Comment by jpownby** [comment]
> [@jpownby](https://github.com/jpownby) Is this still a problem?

Sorry, I am no longer at the company with the code base where I ran into this. I definitely had to make changes locally to assimp to fix all of the issues that I mentioned back when I created the issue, but if new versions of assimp have been released then I no longer have a way to verify the fixes.

Even if I did still have access to the code, however, I no longer remember what assets I used to discover the problem, but my second comment about irrXMLWrapper.h gives at least one potential clue: At the time I was using the test models that were part of assimp to verify different formats and our software wouldn't have done anything with the Irrlicht format otherwise which suggests that at least one of the problems that I ran into was probably with a UTF-16 Irrlicht file that was one of your example files. If you could find that and try it out it might be a way to at least verify with one example whether UTF-16 were being handled correctly. (I kind of have a feeling that there were other UTF-16 files that were problematic, but if one example were handled correctly it would at least be reasonable confirmation of fixes.)

Sorry I can't be of more help than that, good luck!

**Comment by tellypresence** [comment]
@jpownby Thank you for following up.  There were some fixes for UTF-16 irrlicht support that went in in the last year, so hopefully this was fixed

**Comment by jpownby** [comment]
> [@jpownby](https://github.com/jpownby) Thank you for following up. There were some fixes for UTF-16 irrlicht support that went in in the last year, so hopefully this was fixed

I just looked in the code and my guess is that it's not fixed.
From https://github.com/assimp/assimp/blob/275eca9535a23ee870aed9adaa6156d354ac37c8/code/Common/BaseImporter.cpp#L409

```
        std::vector<unsigned char> output;
        utf8::utf16to8(data.begin(), data.end(), back_inserter(output));
        return;
```
I wasn't able to find the definition of utf8::utf16to8() just using a GitHub web browser, but if my assumption is correct that `data.begin()` and `data.end()` are inputs and `back_inserter(output)` is the output then this has the same problem that the temporary variable `output` is just discarded and so any conversion doesn't leave the function.

Without seeing the implementation of the function I can't tell whether the BOM is being skipped in it, so maybe that has been fixed. But this seems like something that shouldn't be hard to test... Can't you just convert a file to UTF-16 and try it? (This is easy in e.g. Notepad++)

Also, the UTF-32 code in the same function appears to also still have the same problem with discarding output:
https://github.com/assimp/assimp/blob/275eca9535a23ee870aed9adaa6156d354ac37c8/code/Common/BaseImporter.cpp#L389
