### ISSUE TITLE
Bug: [MSVC] Compile error in assimp\code\AssetLib\IFC\IFCLoader.cpp with c++20 or later

### ISSUE THREAD

**Issue by NEIL-smtg** [assimp/assimp#5798]
**Describe the bug**
Hi, I work on MSVC compiler testing, and we regularly build popular open-source project including Assimp, with development builds of MSVC in order to find and fix regressions before they ship and cause problems for you.

Recently, as I build Assimp with c++latest, I encountered the error as following:
```c++
C:\gitP\assimp\assimp\code\AssetLib\IFC\IFCLoader.cpp(357,18): error C2666: 'Assimp::STEP::operator ==': overloaded functions have similar conversions [C:\gitP\assimp\assimp\build_amd64\code\assimp.vcxproj]
C:\gitP\assimp\assimp\code\AssetLib\Step\STEPFile.h(583,13): could be 'bool Assimp::STEP::operator ==<Assimp::STEP::Lazy<Assimp::IFC::Schema_2x3::IfcUnitAssignment>>(const std::shared_ptr<Assimp::STEP::LazyObject> &,T)' [synthesized expression 'y == x'] with
[
     T=Assimp::STEP::Lazy<Assimp::IFC::Schema_2x3::IfcUnitAssignment>
]
C:\gitP\assimp\assimp\code\AssetLib\IFC\IFCLoader.cpp(357,18):or 'built-in C++ operator==(T, T)' with
[
    T=Assimp::IFC::Schema_2x3::IfcUnitAssignment
]
C:\gitP\assimp\assimp\code\AssetLib\IFC\IFCLoader.cpp(357,18): while trying to match the argument list '(const Assimp::STEP::Lazy<Assimp::IFC::Schema_2x3::IfcUnitAssignment>, nullptr)'
```

**To Reproduce**
1. open x64 native tools command prompt for vs2022
2. git clone https://github.com/assimp/assimp.git
3. mkdir assimp\assimp\build_amd64
4. cd build_amd64
5. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set _CL_= /std:c++latest
6. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 .. 2>&1
7. msbuild /m /p:Platform=x64 /p:Configuration=Release Assimp.sln /t:Rebuild 2>&1

Build log: [assimp_log.txt](https://github.com/user-attachments/files/17254557/assimp_log.txt)

**Expected behavior**
It compiles.

**Screenshots**
None

**Platform (please complete the following information):**
 - OS: Windows Server 2022 Datacenter x64 bit
 - Browser: -
 - Version 21H2

**Additional context**

**Comment by copycd** [comment]
How about the code below?

if (conv.proj.UnitsInContext.obj == nullptr)

**Comment by NEIL-smtg** [comment]
@copycd `conv.proj.UnitsInContext.obj == nullptr` is still having the same error, but `!conv.proj.UnitsInContext.obj` works

**Comment by shameekganguly** [comment]
@kimkulling are you sure that the issue was fixed with https://github.com/assimp/assimp/pull/6006? https://github.com/assimp/assimp/pull/6006/files only shows an update to the copyright year range.

**Comment by limdor** [comment]
I agree with @shameekganguly, this does not seem to be fixed. Also I just tried with 6.0.2 and the problem still persists.
@kimkulling can you please reopen it?
