### ISSUE TITLE
re-consider using "projects" in favour of pseudo-epics

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#6334]
i understand that a project with >3000 issues needs some proper way to organize bug reports.

however, i find the semantics you arbitrarily assigned to the "Closed (not planned)" functionality of github a bit annoying (afaiu, the semantics you assign to it is: "we acknowledge that this bug exists and deserves fixing; however we currently do not have the resources to do so"; otoh my personal understanding of "Closed (not planned)" is: "you may think that this is an issue, but we do not agree; we have no plans whatsoever of ever fixing this issue")

the problem I'm having is, that some tooling seems to agree with my interpretation, marking issues as indeed resolved while they are not.
that is: i'm maintaining the Debian packages of "assimp".
within Debian, we have our own bug tracker for each package (mostly to track distro specific bugs; but also to track security related issues).
for whatever reasons, assimp has a rather high number of CVEs, resulting in [several dozens of security bugs tracked by Debian](https://bugs.debian.org/cgi-bin/pkgreport.cgi?repeatmerged=no&src=assimp)

now the Debian bug tracker automatically marks bugs as "fixed upstream" once it detects that an issue has been marked as resolved in the upstream issue tracker. a GitHub ticket that gets **Closed** (for whatever reasons), is thus marked as resolved.
which - for me - means a lot of extra work, because all the CVEs are no marked as resolved and i have to manually check the actual state by digging through your epics and the history of each issue.

as I said above: i do understand that you need a way to organize and prioritize your bugs, to avoid duplicate work and what not.

However, for me it seems that you are trying to re-implement a workflow in an environment that is not up to it.

otoh, GitHub does offer per-project [Projects](https://github.com/assimp/assimp/projects), which is a kanban-board like way to organize issues.
just move your (**open**) tickets from "To Do" (currently: "Closed (not planned)") to "In Progress" (currently: "Re-Opened").
and "Closed" tickets automatically get moved to the "Done" column.
or use whatever columns you like.

**Comment by tellypresence** [comment]
@umlaeute Thank you for your thoughts, you make some good points.  I had hoped github would support a `Backlog` status, to indicate an issue was important and deserved future attention pending resource availability, but that doesn't seem to be on the roadmap -- I agree that using `Closed - not planned` is a poor substitute.

@kimkulling Do you think github [Projects](https://github.com/assimp/assimp/projects?query=is%3Aopen) might be of use?

As a compromise, have reopened [all issues with `Security Risk` label](https://github.com/assimp/assimp/issues?q=is%3Aissue%20parent-issue%3Aassimp%2Fassimp%236141) to make it easier on downstream maintainers trying to stay up with CVE statuses

**Comment by kimkulling** [comment]
Hi All, 

I was optimistic when seeing the idea of getting Epics. But also for me it getting hard to see which topics are urgend and which not. It was worth of trying it out. But for me it feels wrong.

The idea to use the Project for that could be a good idea. Unfortunately we get not payed for doing this work. I cannot tell peopple tdo this. We all doing this for free. 

So Using Projects could help.

My thoughts

**Comment by tellypresence** [comment]
> So Using Projects could help.

I think someone with admin access will need to set up and configure Projects

**Comment by tellypresence** [comment]
@kimkulling Also please check whether we can add a [custom single select field](https://docs.github.com/en/issues/planning-and-tracking-with-projects/understanding-fields/about-single-select-fields) for issue progress status, to better reflect whether issue is
- `Backlog`
- `In progress`
- `Testing`/`Verification`


Could probably also use a custom single select field for priority e.g.
- `Urgent`/`High priority`
- `Medium priority`
- `Low priority`


Then by applying a few filters should be able to quickly isolate urgent issues that haven't been started etc.

**Comment by tellypresence** [comment]
@kimkulling I can set up Projects if you like, but would need a couple of extra permissions

**Comment by kimkulling** [comment]
We already have a project. But using another one for planning sounds good to me.

**Comment by kimkulling** [comment]
Which permissions will you need?

**Comment by tellypresence** [comment]
> Which permissions will you need?

Would suggest starting by checking whether I'm already in the project collaborators list:
- [Managing access of an existing collaborator on your project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects#managing-access-of-an-existing-collaborator-on-your-project)

If not, would probably need an invitation:
- [Managing [project] access for teams and individual members of your organization](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects#managing-access-for-teams-and-individual-members-of-your-organization)

It's hard for me to tell since I don't have permission to browse the admin dashboard, but if access is per-Project, it may be that you need to create a new planning Project, then send invite with write access specifically for that new Project(?)  Might take a few cycles to figure it out 😅

**Comment by tellypresence** [comment]
> We already have a project. But using another one for planning sounds good to me.

Note: 
The assimp kanban is organizational (not repo) level, to view need to go [here](https://github.com/orgs/assimp/projects/2/views/1)

If people open the "Projects" tab for the `assimp` repo itself, they'll see "Welcome to projects" but no actual projects available to browse

<img width="2770" height="1566" alt="Image" src="https://github.com/user-attachments/assets/ffa533a6-fae5-4a9e-bb0e-fa7985b83c7c" />

**Comment by kimkulling** [comment]
I have send you an invitation as an admin. Let's try this way. I will take care of the older issues. And thanks a lot for all your great work. It helped me a lot to get a nuch better view onto our open tasks, issues and feature requests.

**Comment by tellypresence** [comment]
> I have send you an invitation as an admin

Thank you -- invitation hasn't arrived yet, will look out for it

**Comment by tellypresence** [comment]
@kimkulling
Once you've sent the invite, I can look at providing link to [assimp organization kanban](https://github.com/orgs/assimp/projects/2/views/1) from [assimp repo project page](https://github.com/assimp/assimp/projects) to make it easier to view

**Comment by kimkulling** [comment]
Done?

**Comment by umlaeute** [comment]
I guess the closed backlog issues still need to be reopened.

(I'm currently afk, so apologies if I missed of this was already the case)

**Comment by tellypresence** [comment]
> Done?

Hasn't arrived yet, will look for it
