### ISSUE TITLE
realpath and mingw32-64

### ISSUE THREAD

**Issue by Lectem** [assimp/assimp#660]
Realpath isn't available on mingw32-64, so it should be added to the list of checked systems here: https://github.com/assimp/assimp/blob/master/code/DefaultIOSystem.cpp#L138
Perhaps use _WIN32 instead or check for realpath at configuration time with cmake using CHECK_FUNCTION_EXISTS ?

**Comment by kimkulling** [comment]
Should be fixed now.

**Comment by Lectem** [comment]
Not fixed, you need to use _WIN32 instead of _MSC_VER, realpath doesn't exist in mingw32-64.

**Comment by kimkulling** [comment]
I don't understand this: http://pubs.opengroup.org/onlinepubs/000095399/functions/realpath.html Realpath works for me with mingw-4.81.1 for Windows and realpath is part of stdlib.h. We just want to use _fullpath when having a Visual-Studio compiler.

**Comment by kimkulling** [comment]
Could you please post your error. When using _WIN32 olny we will get another issue again. So we need to find a different solution for this issue, sorry.

**Comment by Lectem** [comment]
You are probably talking about the standard mingw from http://www.mingw.org/ and not mingw-w64  from http://mingw-w64.org (sorry, I didn't give enough information there).

MinGW-w64 (at least not the 5.1, x86_64-5.1.0-posix-seh-rt_v4-rev0) doesn't have realpath.

If you really want to aim for cross-platform I think the best way to do it is to use CMake to detect the presence of realpath with check_function_exists, and add a defintion or some configuration header.
It would probably be good for embedded development on devices not POSIX compliant.

**Comment by kimkulling** [comment]
I am just installing the compiler suite. I will try to reproduce the issue first.

**Comment by afiskon** [comment]
Same issue here.

Maybe:

```
if defined(_MSC_VER) || defined(__MINGW32__)
```
?

**Comment by kimkulling** [comment]
I tried the mingw version and it works fine on my machine. So I cannot reproduce your issue here with the mingw-version ( latest from hp ).

Could you check this on your machine please: if defined(_MSC_VER) || defined(__MINGW32__) works this for you?

**Comment by afiskon** [comment]
@kimkulling affirmative :)

**Comment by Lectem** [comment]
@kimkulling it works but commit f5c8f7b is missing the `#` for the `#if`

**Comment by afiskon** [comment]
TWIMC - typo fixed https://github.com/assimp/assimp/commit/7ed32fd5a9bdefb23fb281ec98dce3383383e51a

**Comment by selony** [comment]
Hello,

I've got this error too:

code\DefaultIOSystem.cpp:143:32: error: 'realpath' was not declared in this scope
         ret = realpath(in, _out);

Yesterday I tried to compile and worked fine. Today seems to be something wrong. 

Checked the file and got, do I miss something?

#ifdef _MSC_VER
	ret = ::_fullpath( _out, in, PATHLIMIT );
#else
        // use realpath
        ret = realpath(in, _out);
#endif

Regards
